### ISSUE TITLE
Fix: ```bundle update --bundler``` does not update bundler; results in console errors when running ```bundle [whatever]```

### ISSUE THREAD

**Issue by SKBruck** [allhandsactive/site#181]
Known issue. Details here: https://github.com/rubygems/rubygems/issues/5236

Error received: ```Calling DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call DidYouMean.correct_error(error_name, spell_checker)' instead.```

Also a known issue, related to bundler not updating in lockfile. Details here: https://github.com/rubygems/rubygems/issues/5234

Proposed fix is here: https://github.com/rubygems/rubygems/issues/5236#issuecomment-1002527967.

**Comment by SKBruck** [comment]
Both options to update bundler result in the ruby platform being replaced by ```x84_64-linux```. Running ```bundle lock --add-platform ruby``` does not resolve the problem. More research into https://github.com/rubygems/rubygems/issues/5830 needed to fix this. Old bundler version is not breaking the site, just throwing an error about DidYouMean, so this issue shouldn't interrupt site updates.

**Comment by artlogic** [comment]
@SKBruck is this resolved, or still an issue?

**Comment by SKBruck** [comment]
This is resolved. Closing this out.
