### ISSUE TITLE
Add Mastodon link to social footer

### ISSUE THREAD

**Issue by vielmetti** [allhandsactive/site#185]
The Mastodon link at @aha@a2mi.social is omitted from the bottom footer on the main page of the site.

**Comment by artlogic** [comment]
Good catch @vielmetti - any chance you feel up to creating a PR for this?

**Comment by vielmetti** [comment]
@artlogic I can try a PR. What version of Font Awesome are we using? I can't figure out where that gets pulled in. And do we have a test system where I can see what the PR looks like?

**Comment by artlogic** [comment]
It's being pulled in from the parent theme: https://mmistakes.github.io/minimal-mistakes/

Remote PRs don't get built on the test system, but local ones do. I'll get you access to this repo so you can take advantage of that.

**Comment by artlogic** [comment]
All ready for you @vielmetti

**Comment by vielmetti** [comment]
Some looking at this:

Since the latest release of Minimal Mistakes, Font Awesome has made some changes. It looks like there are unreleased bits that track those changes, e.g. at https://github.com/mmistakes/minimal-mistakes/pull/3599 .

The Mastodon icon was introduced in Font Awesome 5.8.0: https://github.com/FortAwesome/Font-Awesome/issues/17980

I was able to put together a patch that added the link, but didn't add the icon. I'll get that as a PR to review, but I don't think it will be ready to merge just yet.

**Comment by vielmetti** [comment]
I got the link into the footer in #186 but I'm puzzled by Font Awesome, and several attempts to load the glyph (which is supported only in FA 5.8.0) haven't worked.

**Comment by artlogic** [comment]
@SKBruck any insight here?

**Comment by SKBruck** [comment]
I can try to get minimal mistakes updated and see if that will resolve issues. I had run into an issue updating which is why it hasn't been pushed as a pr yet. I'm wrapping gifts so I'll look at what's up again and try to get a PR pushed tomorrow after family stuff. I can't currently add details because I'm afk, but iirc the problem was local to my machine.

**Comment by artlogic** [comment]
Done!
