### ISSUE TITLE
Make header banner images/text/buttons specific to the context of the page they're on

### ISSUE THREAD

**Issue by zandi** [allhandsactive/site#21]
Right now the large banner images are "become a member" or "donate" on every page. We should make them more relevant to whatever page they're on. For example, the "Contact Us" could be a "mailto:" and "how to get here" buttons.

Taking ideas on what each page should have.

**Comment by artlogic** [comment]
@zandi pretty sure we're good here - can you review the site and close if you agree, or add more detail you don't?

**Comment by black-august** [comment]
banner images seem to be different, and buttons have functionality as described. can we close this?

**Comment by artlogic** [comment]
@zandi ?

**Comment by zandi** [comment]
I entirely forget what this issue was originally about and have been pretty
busy with work and life. I'll take a look but considering the issue is so
old I wouldn't be surprised if it's been fixed

**Comment by artlogic** [comment]
If you find it's been resolved, please close it out. Thanks!

**Comment by zandi** [comment]
Did my due diligence and looked things over, I'd say this is closed. Thanks!
