### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by JLDohm** [allhandsactive/site#38]
I can have a stab at creating one, but I wanted to see if once already existed first.

**Comment by artlogic** [comment]
@JLDohm I don't think one exists. If you drop one here, @SKBruck can add it.

**Comment by JLDohm** [comment]
I created a favicon, but I can't upload here.
https://drive.google.com/file/d/1KgTezzSUi_ZUT5zheIsRx3ldYWiQCWft/view?usp=sharing
@SKBruck can you add it?

**Comment by artlogic** [comment]
@JLDohm what's going on with this? Is the PR flow you've been using not working?

**Comment by JLDohm** [comment]
I was honestly just following the advice of your previous comment. If all that needs to happen is a pr to add favicon.ico, I can do that, but I think that some change to each pages header is required to make it actually work? I didn't know how to do that and I moved on to things that I was actually capable of doing.

**Comment by artlogic** [comment]
The one that I'm about to merge is a good start - let's try using this site to get a bit better: https://realfavicongenerator.net/

**Comment by black-august** [comment]
we can close this, the favicon is up and working
