### ISSUE TITLE
Subscribe button should work

### ISSUE THREAD

**Issue by artlogic** [allhandsactive/site#44]
Talk to me about mailchimp info.

**Comment by larryworks** [comment]
What do you want to know about mailchimp?

**Comment by artlogic** [comment]
@larryworks in particular we need to make the subscribe button on the new site go to our public mailchimp - I've got the login info so this should be relatively trivial, *I think*

**Comment by artlogic** [comment]
Looks like there's a button on the members page too. Re-opening.

**Comment by artlogic** [comment]
Fixed.
