### ISSUE TITLE
Update repo website link

### ISSUE THREAD

**Issue by ishotjr** [allhandsactive/site#74]
The URL linked to from the repo:

https://www.allhandsactive.org/

results in:

`NET::ERR_CERT_COMMON_NAME_INVALID`

when navigated to. This is a [known issue](https://github.com/isaacs/github/issues/1675) but can be ameliorated via DNS. However, quickest solution for now might be to just update the URL to point to:

https://allhandsactive.org/

:bowtie:

**Comment by artlogic** [comment]
Done.

I'm frustrated that this is still an issue, but I think it's also relatively minor. The work it would take to solve this vs. the scope of the problem makes me think maybe this is one we let other folks complain about until github fixes it.
