### ISSUE TITLE
Add Paypal options

### ISSUE THREAD

**Issue by l0gik** [allhandsactive/site#76]
Right now, the only way to pay for things is via our fundraiser link.  We should have a separate, general-purpose way to pay for things, e.g. dues for those members who are not on recurring payments, ways to donate an arbitrary amount of money, and a way to pay for classes/other things (historically done via the "donation" method of payment).

Related to #61, but we also need non-donation options -- one-time and recurring, at standard, student, family, co-working(?) tiers -- for new or existing members.

**Comment by artlogic** [comment]
I think #80 will cover this.

**Comment by artlogic** [comment]
@l0gik please check the latest site and see if we've covered this
